services:
  concierge-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./wasp-core:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/concierge
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=concierge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: