services:
  - type: web
    name: lacasita-booking
    runtime: docker
    dockerfilePath: Dockerfile.prod
    env: 
      NODE_ENV: production
      DATABASE_URL: postgres://user:pass@host:port/db
    autoDeploy: true
    region: ohio
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lacasita-db
          property: connectionString

databases:
  - name: lacasita-db
    plan: free
    region: ohio
    databaseName: lacasita
    user: lacasita_user